name: Release - Deploy

on:
  push:
    branches:
      - release

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: release

    - name: Nodejs Setup
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Angular
      run: npm i -g @angular/cli

    - name: Install Dependencies
      run: npm i

    - name: Lint
      run: ng l

    - name: Build
      run: ng b -c production