name: Release - Deploy

on:
  push:
    branches:
      - release

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: release

    - name: Nodejs Setup
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Angular
      run: npm i -g @angular/cli

    - name: Install Dependencies
      run: npm i

    - name: Lint
      run: ng l

    - name: Build
      run: ng b -c production

    - name: Build, Push and Release a Docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}